service: ggg-mkt-spot-request

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.12
  region: ap-southeast-1
  role: arn:aws:iam::196761233825:role/lambda-ec2-spot-scheduler-role

functions:
  checkSpotInstance:
    handler: assign_eip.check_spot_instance
    environment:
      SPOT_FLEET_REQUEST_ID: sfr-bc6b6dd2-8aeb-40bb-803a-09ca6a3df0b2
      ALLOCATION_ID: eipalloc-0f53833ea8ff2874c
    events:
      - schedule: rate(5 minutes)
