service: modify-spot-request

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.12
  region: ap-southeast-1
  role: arn:aws:iam::196761233825:role/lambda-ec2-spot-scheduler-role

functions:
  modifySpotRequestOn:
    handler: handler.lambda_handler
    environment:
      SPOT_FLEET_REQUEST_ID: sfr-396ac24b-be95-42d6-9df1-4d7658f71296
      NEW_TARGET_CAPACITY: 0
    events:
      - schedule:
          rate: cron(0 2 * * ? *)

  modifySpotRequestOff:
    handler: handler.lambda_handler
    environment:
      SPOT_FLEET_REQUEST_ID: sfr-396ac24b-be95-42d6-9df1-4d7658f71296
      NEW_TARGET_CAPACITY: 0
    events:
      - schedule:
          rate: cron(30 14 * * ? *)

  checkSpotInstance:
    handler: assign_eip.check_spot_instance
    environment:
      SPOT_FLEET_REQUEST_ID: sfr-396ac24b-be95-42d6-9df1-4d7658f71296
      ALLOCATION_ID: eipalloc-0fcb2f68adda9bfbb
    events:
      - schedule: rate(30 minutes)
